#
# S2 File.R
#
# Block-forward (BF) approach with INGARCH models implemented in tscount package.
# This function calls S1 File.R.
#
# Several examples of usage:
#
# Example with simulated count data (Ysim) and linearly related covariates such as 
# {Temp}, {PM25, PM10}, {NOx, NO2}, {O3}, {SO2}, {CO} organized in 6 ordered blocks (Example 1).
#
# An example with 4 ordered blocks {Temp, PM25, PM10, NOx, NO2}, {O3}, {SO2}, {CO} 
# for illustrative purposes of blocks manipulation is also presented (Example 2).
#
# Additionally, an example with lagged versions of a single covariate and 3 blocks
# of covariates is also shown (Example 3).
# 
# The implementation of the BF approach can deal with missing covariates and, in this example, 
# PM25, SO2 and CO are considered missing data.
#
#
# Development/Implementation
#   Ana Martins (a.r.martins@ua.pt)
#   University of Aveiro, Portugal, December 2020
#   R version 3.6.2; tscount version 1.4.2;
#
# Reference:
# Martins A, Scotto M, Deus R, Monteiro A, Gouveia S (2021) 
# Association between respiratory hospital admissions and air pollution in Portugal: a count time series approach
#
#

############
# Install packages used in this tool (if needed)
############
install.packages("tscount")
install.packages("data.table")
install.packages("plotrix")
install.packages('tsDyn')

############
# Load packages used in this tool
############
library(tscount)
library(MASS)
library(tsDyn)

############
# Data simulation
############

# Set seed for reproducible results.
#
set.seed(12)

# Set length of the time series.
#
len=365

# Simulate covariates.
# In this example, covariates are generated by a Vector Autoregressive (VAR) model with 
# multivariate normal distributed innovations.
# Simulation is performed with function VAR.sim tsDyn package
# For further details ?VAR.sim
#
# The parameters mu and variance-covariance matrix of the innovations
# as well as the VAR coefficients were set following the VAR model fitting 
# to the observed covariates in VALO location (see Martins et al, 2021).
#

mu <- c(21.5, 69, 350, 110 , 80)

cov.matrix = matrix(c(36.563186,    8.965374,   -28.92545,  -24.86195,   67.68020,
                      8.965374,  699.761430,  1222.07154,  189.53708,  105.20470,
                      -28.925448, 1222.071545, 14319.78890, 1042.49263, -210.04697,
                      -24.861952,  189.537077,  1042.49263, 1617.76656,  -50.85043,
                      67.680204,  105.204703,  -210.04697,  -50.85043,  658.55811), 
                    nrow = 5)

MVDistr <- mvrnorm(n=len+1, mu = mu, Sigma=cov.matrix)

VARmodel <- lineVar(MVDistr, lag=1)
coefs<- VARmodel$coefficients
innov <- VARmodel$residuals  
TsSim <- VAR.sim(B=coefs, n=len, innov = innov)

TsSim <- as.data.frame(TsSim)
colnames(TsSim) <- c('Temp', 'PM10', 'NOx','NO2', 'O3')

xreg <- TsSim[1:3]
xreg <- cbind(xreg, TsSim[,5])
colnames(xreg)[4] <- 'O3'

# Simulate a time series of counts with reference parameters and external covariates
# p = 1, beta_1 = 0.2, 
# q = 1, alpha_1 = 0.5,
# link = log
# distr = nbinom
# distrcoefs = 2
# external covariates: Temp, PM10, NOx and O3
# external covariates coefficients: -0.02, 0.004, 0.001, -0.005
#
Ysim <- tsglm.sim(len, param = list(intercept = 1, past_obs = c(0.2), 
                                    past_mean = c(0.5), 
                                    xreg=c(-0.02, 0.004,0.001, -0.0005)), 
                  model = list(past_obs = 1, past_mean = 1, external = TRUE), 
                  link = "log", distr = "nbinom", distrcoefs = 2, xreg = xreg)


# Visualise the simulated time series (counts and covariates).
#
par(mfrow=c(3,2))
plot(Ysim$ts, main = "Hosp Adm (Response) TS")
plot(TsSim$Temp, main = 'Temperature', type = 'l')
plot(TsSim$PM10, main = 'PM10', type = 'l')
plot(TsSim$NOx, main = 'NOx', type = 'l')
plot(TsSim$NO2, main = 'NO2', type = 'l')
plot(TsSim$O3, main = 'O3', type = 'l')

############
# Load function tsglm_forward 
############
# "S1 File.R" either is in the current directory... 
source("S1 File.R")
# ... or include its path, if not in the current directory e.g. source("C:/Users/Your path to S1 File/S1 File.R").

############
# Estimate INGARCH(p,q) model with BF approach.
############
# p=1
# q=1
# link = log
# distr = nbinom
# see Martins et al (2021)
#

# Example 1:
# L = {Temp(t)}, {PM25(t), PM10(t)}, {NOx(t), NO2(t)}, {O3(t)}, {SO2(t)}, {CO(t)}
# L[[i]][j], i = 1, ..., 6; j = 1, .., N_i, N_i = number of covariates in the ith-block
# e.g: L[[1]][j], j = 1; L[[2]][j], j = 1,2; ...
#
example1 <- forward_tsglm(Y = list(response = Ysim$ts, model = list(past_obs = 1, past_mean = 1), link = 'log', distr = 'nbinom'),
                          covar = list(temp = TsSim$Temp,
                                       PM = list(PM25 = NULL, PM10 = TsSim$PM10),
                                       NO = list(NOx = TsSim$NOx, NO2 = TsSim$NO2),
                                       O3 = TsSim$O3,
                                       SO2 = NULL,
                                       CO = NULL))


# see summary of the fitted model
# In example1, Temp(t) and PM10(t) enter the the model (one from each of the first two blocks) 
# and no other covariates enter the model.
summary(example1) 


# Example 2:
#
# L = {Temp(t), PM25(t), PM10(t), NOx(t), NO2(t)}, {O3(t)}, {SO2(t)}, {CO(t)}
# i = 4 (blocks)
# L[[i]][j], i = 1, ..., 4; j = 1, .., N_i
# e.g: L[[1]][j], j = 1,2,3,4,5; L[[2]][j], j = 1; ...
#
example2 <- forward_tsglm(Y = list(response = Ysim$ts, model = list(past_obs = 1, past_mean = 1), link = 'log', distr = 'nbinom'),
                          covar = list(mix = list(temp = TsSim$Temp, PM25 = NULL, PM10 = TsSim$PM10, NOx = TsSim$NOx, NO2 = TsSim$NO2),
                                       O3 = TsSim$O3,
                                       SO2 = NULL,
                                       CO = NULL))


# see summary of the fitted model
# In example2, Temp(t) is chosen from all the covariates in the first block,
# and no variables in the 2nd, 3rd and 4th block enter the model.
summary(example2)


# Example 3: 
# L = {Temp(t);Temp(t-1)}, {PM25(t), PM10(t)}, {NOx(t), NO2(t)}
# i = 3 blocks
# Lagged variables of a same predictor can be evaluated by being considered in that block
# e.g. {Temp} = {Temp.Lag0, Temp.Lag1}
#
# Lagged variables
Y <- Ysim$ts[2:len]                # Y(t)
tempLag0 <- TsSim$Temp[2:len]      # Temp(t)
tempLag1 <- TsSim$Temp[1:(len-1)]  # Temp(t-1)
tempList <- list()
tempList[[1]] = tempLag0
tempList[[2]] = tempLag1
names(tempList) = c('Temp.Lag0', 'Temp.Lag1')
pm10 <- TsSim$PM10[2:len]          # PM10(t)
nox <- TsSim$NOx[2:len]            # NOx(t)
no2 <- TsSim$NO2[2:len]            # NO2(t)

example3 <- forward_tsglm(Y = list(response = Y, model = list(past_obs = 1, past_mean = 1), link = 'log', distr = 'nbinom'),
                          covar = list(temp = tempList,
                                       PM = list(PM25 = NULL, PM10 = pm10),
                                       NO = list(NOx = nox, NO2 = no2)))


# see summary of the fitted model
# In example3, Temp(t) is chosen over Temp(t-1) in the first block,
# and PM10(t) is chosen in the second block, and no other variables are chosen.
summary(example3)


#for further details on object example1/example2/example3 see ?tsglm

